import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import CustomMouseArrow from "@/components/animated/customcoursor";

export const metadata: Metadata = {
  title: "𝒜𝓁𝒾'𝓈 𝙭 𝒫o𝓇𝓉𝒻o𝓁𝒾o",
  description: "Generated by Syed Ali Askari Zaidi",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body>
          <CustomMouseArrow />
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </body>
      </html>
    </>
  );
}
